version: '3.4'

services:
  app:
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local