# docker-compose.test.yml
version: '3.4'

services:
  app:
    extends:
      file: ./docker-compose.yml
      service: app
    command: ['npm', 'run', 'start:test']

  db:
    extends:
      file: ./docker-compose.yml
      service: db
    volumes:
      - postgres_data_test:/var/lib/postgresql/data 

volumes:
  postgres_data_test:
    driver: local
